// Changes' visual identity: bright blue on near-white, near-black
// extra-bold headings, light-blue selected states, and purple/gradient
// reserved for the adaptive engine ("periodização", the ✦ star).
//
// Token keys are unchanged so every `useTheme().colors.*` call site keeps
// working; only the values move.
export const Colors = {
  dark: {
    // Dark mode is a deep navy, not a neutral black.
    background: '#0B1220',
    surface: '#141C2B',
    surfaceVariant: '#1B2436',
    surfaceHighlight: '#233047',
    primary: '#4B82FF',
    primaryContainer: '#1C2E5A',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#C9DAFF',
    secondary: '#32D74B',
    secondaryContainer: '#123A1C',
    onSecondary: '#04210A',
    accent: '#9B7BFF',
    accentContainer: '#2C2350',
    onAccent: '#120A2A',
    error: '#FF453A',
    errorContainer: '#3A1512',
    onError: '#FFFFFF',
    success: '#32D74B',
    warning: '#FFB340',
    text: '#F2F4F8',
    textSecondary: '#9BA3B4',
    textTertiary: '#6B7482',
    border: '#263149',
    borderLight: '#33405C',
    overlay: 'rgba(0,0,0,0.6)',
    shadow: 'rgba(0,0,0,0.5)',
    chip: '#1B2436',
    chipSelected: '#1C2E5A',
    rest: '#4B82FF',
    pr: '#FFB340',
    warmup: '#FFB340',
    dropset: '#9B7BFF',
    failure: '#FF453A',
    amrap: '#40C8E0',
    calendarWorkout: '#4B82FF',
    calendarToday: '#4B82FF',
    streak: '#FFB340',
  },
  light: {
    background: '#F7F8FA',
    surface: '#FFFFFF',
    surfaceVariant: '#F4F5F7',
    surfaceHighlight: '#ECEEF1',
    primary: '#2F6BFF',
    primaryContainer: '#E4EDFF',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#1B44B8',
    secondary: '#34C759',
    secondaryContainer: '#DFF5E3',
    // BUGFIX (WCAG AA audit): white text/icons on this green measure only
    // ~2.2:1 contrast — well under the 4.5:1 minimum for normal text. A
    // dark, near-black tone against #34C759 clears ~7.7:1.
    onSecondary: '#08201C',
    accent: '#7C4DFF',
    accentContainer: '#ECE4FF',
    onAccent: '#FFFFFF',
    error: '#FF3B30',
    errorContainer: '#FFE5E3',
    onError: '#FFFFFF',
    success: '#34C759',
    warning: '#F5A623',
    text: '#16181D',
    textSecondary: '#8A8F98',
    textTertiary: '#B4B8C0',
    border: '#EAEBEE',
    borderLight: '#F1F2F4',
    overlay: 'rgba(0,0,0,0.4)',
    shadow: 'rgba(16,24,40,0.08)',
    chip: '#F4F5F7',
    chipSelected: '#E4EDFF',
    rest: '#2F6BFF',
    pr: '#F5A623',
    warmup: '#F5A623',
    dropset: '#7C4DFF',
    failure: '#FF3B30',
    amrap: '#00B8D4',
    calendarWorkout: '#2F6BFF',
    calendarToday: '#2F6BFF',
    streak: '#F5A623',
  },
};

export type Theme = typeof Colors.dark;
