// GymForge visual identity.
//
// Token keys are shared across light / dark / oled so every
// `useTheme().colors.*` call site keeps working; only the values move.
//
// - light: bright blue on near-white (daytime / accessibility)
// - dark:  navy cyber-blue (elevated cards on near-black)
// - oled:  true-black panels + neon accents (battery + AMOLED punch)

export const Colors = {
  dark: {
    // Near-black navy for elevated-card contrast.
    background: '#070B14',
    surface: '#121A28',
    surfaceVariant: '#1A2436',
    surfaceHighlight: '#243044',
    // Vibrant cyber blue
    primary: '#3D8BFF',
    primaryContainer: '#15305F',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#D6E6FF',
    secondary: '#3DFF8A',
    secondaryContainer: '#0E3A22',
    onSecondary: '#04150C',
    // Adaptive / premium accent (violet, not competing with primary)
    accent: '#A78BFA',
    accentContainer: '#2A1F4D',
    onAccent: '#F5F0FF',
    error: '#FF4D55',
    errorContainer: '#3F1418',
    onError: '#FFFFFF',
    success: '#3DFF8A',
    warning: '#FFC14D',
    text: '#F5F7FB',
    textSecondary: '#A8B0C0',
    textTertiary: '#6E7789',
    border: '#2A3548',
    borderLight: '#364457',
    overlay: 'rgba(0,0,0,0.65)',
    shadow: 'rgba(0,0,0,0.55)',
    chip: '#1A2436',
    chipSelected: '#15305F',
    rest: '#3D8BFF',
    pr: '#FFC14D',
    warmup: '#FFC14D',
    dropset: '#A78BFA',
    failure: '#FF4D55',
    amrap: '#2EE6FF',
    calendarWorkout: '#3D8BFF',
    calendarToday: '#3D8BFF',
    streak: '#FFC14D',
  },
  oled: {
    // True black — pixels off on AMOLED.
    background: '#000000',
    surface: '#0A0A0C',
    surfaceVariant: '#121218',
    surfaceHighlight: '#1A1A24',
    // Neon cyan primary
    primary: '#00E5FF',
    primaryContainer: '#003A44',
    onPrimary: '#001014',
    onPrimaryContainer: '#B8F7FF',
    // Neon mint
    secondary: '#39FFB0',
    secondaryContainer: '#003D2A',
    onSecondary: '#00140E',
    // Neon violet (adaptive / premium)
    accent: '#C77DFF',
    accentContainer: '#2A1040',
    onAccent: '#F8F0FF',
    error: '#FF3B5C',
    errorContainer: '#3A0010',
    onError: '#FFFFFF',
    success: '#39FFB0',
    warning: '#FFD60A',
    text: '#FFFFFF',
    textSecondary: '#A0A8B8',
    textTertiary: '#6A7284',
    // Subtle cyan-tinted hairlines (read as neon edge, not grey boxes)
    border: '#1A2A32',
    borderLight: '#243840',
    overlay: 'rgba(0,0,0,0.78)',
    shadow: 'rgba(0,229,255,0.12)',
    chip: '#121218',
    chipSelected: '#003A44',
    rest: '#00E5FF',
    pr: '#FFD60A',
    warmup: '#FFD60A',
    dropset: '#C77DFF',
    failure: '#FF3B5C',
    amrap: '#39FFB0',
    calendarWorkout: '#00E5FF',
    calendarToday: '#00E5FF',
    streak: '#FFD60A',
  },
  light: {
    background: '#F5F7FB',
    surface: '#FFFFFF',
    surfaceVariant: '#EEF1F6',
    surfaceHighlight: '#E4E9F1',
    primary: '#1F6EFF',
    primaryContainer: '#E0EBFF',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#0B3AA8',
    secondary: '#1FAF54',
    secondaryContainer: '#D8F5E3',
    onSecondary: '#062414',
    accent: '#7C5CFF',
    accentContainer: '#EDE7FF',
    onAccent: '#FFFFFF',
    error: '#E11D2E',
    errorContainer: '#FFE4E6',
    onError: '#FFFFFF',
    success: '#1FAF54',
    warning: '#E59A00',
    text: '#0F141C',
    textSecondary: '#5C6575',
    textTertiary: '#8B93A3',
    border: '#E2E6EE',
    borderLight: '#EBEEF3',
    overlay: 'rgba(0,0,0,0.4)',
    shadow: 'rgba(15,20,28,0.1)',
    chip: '#EEF1F6',
    chipSelected: '#E0EBFF',
    rest: '#1F6EFF',
    pr: '#E59A00',
    warmup: '#E59A00',
    dropset: '#7C5CFF',
    failure: '#E11D2E',
    amrap: '#00A8C2',
    calendarWorkout: '#1F6EFF',
    calendarToday: '#1F6EFF',
    streak: '#E59A00',
  },
};

export type Theme = typeof Colors.dark;
