import { getDatabase } from './database';
import type { WorkoutPlan, PlanExercise, SetType, PlanType, SplitType } from '@/types';

export async function getAllPlans(): Promise<WorkoutPlan[]> {
  const db = await getDatabase();
  const rows = await db.getAllAsync(
    'SELECT * FROM workout_plans ORDER BY updated_at DESC'
  );
  return rows as WorkoutPlan[];
}

/**
 * Plans a person can knowingly pick from a manual picker — the adaptive
 * wizard's own plan list, the weekly planner's "Que plano treinas neste
 * dia?" picker, "Meus Planos". Excludes auto-generated output (adaptive
 * wizard runs, Treino Inteligente, 5/3/1): every "Criar plano novo" run
 * through the wizard inserts a fresh row literally named "Plano Adaptativo"
 * (see generatePlan's customName in utils/planGenerator.ts), so repeating
 * that path leaves every earlier, now-obsolete run's row still in the
 * table — none of those rows was ever meant to be reselected here. A day
 * already assigned to one of these plans from before this filter existed
 * still resolves its own name via the unfiltered list at the call site;
 * this function only governs what's offered going forward.
 */
export function filterUserSelectablePlans(plans: WorkoutPlan[]): WorkoutPlan[] {
  return plans.filter(p => !p.is_auto_generated);
}

export async function getPlanById(id: number): Promise<WorkoutPlan | null> {
  const db = await getDatabase();
  const row = await db.getFirstAsync('SELECT * FROM workout_plans WHERE id = ?', [id]);
  return row as WorkoutPlan | null;
}

export async function createPlan(
  name: string,
  description: string,
  planType: PlanType,
  splitType: SplitType,
  isAutoGenerated: boolean = false
): Promise<number> {
  const db = await getDatabase();
  const result = await db.runAsync(
    'INSERT INTO workout_plans (name, description, plan_type, split_type, is_auto_generated) VALUES (?, ?, ?, ?, ?)',
    [name, description, planType, splitType, isAutoGenerated ? 1 : 0]
  );
  return result.lastInsertRowId as number;
}

export async function updatePlan(plan: WorkoutPlan): Promise<void> {
  const db = await getDatabase();
  await db.runAsync(
    'UPDATE workout_plans SET name = ?, description = ?, plan_type = ?, split_type = ?, updated_at = strftime(\'%s\',\'now\') WHERE id = ?',
    [plan.name, plan.description, plan.plan_type, plan.split_type, plan.id]
  );
}

export async function deletePlan(id: number): Promise<void> {
  const db = await getDatabase();
  await db.runAsync('DELETE FROM workout_plans WHERE id = ?', [id]);
}

export async function duplicatePlan(id: number): Promise<number> {
  const db = await getDatabase();
  const plan = await getPlanById(id);
  if (!plan) throw new Error('Plan not found');
  const exercises = await getPlanExercises(id);
  // Wrapped in a transaction: without it, an interruption partway through
  // copying a multi-day plan's exercises could leave a duplicate with only
  // some of its days/exercises present, with no indication anything was
  // missing.
  let newId!: number;
  await db.withTransactionAsync(async () => {
    newId = await createPlan(`${plan.name} (Copia)`, plan.description, plan.plan_type, plan.split_type);
    for (const ex of exercises) {
      await addExerciseToPlan(newId, ex.exercise_id, ex.sets, ex.reps_target, ex.weight_target, ex.rest_seconds, ex.set_type, ex.superset_group, ex.notes, ex.order_index, ex.day_label ?? '', ex.day_index ?? 0, ex.tempo ?? '');
    }
  });
  return newId;
}

export async function getPlanExercises(planId: number): Promise<PlanExercise[]> {
  const db = await getDatabase();
  const rows = await db.getAllAsync(
    'SELECT * FROM plan_exercises WHERE plan_id = ? ORDER BY day_index, order_index',
    [planId]
  );
  return rows as PlanExercise[];
}

/** Distinct training days of a plan, in order (e.g. Push / Pull / Pernas). */
export async function getPlanDays(planId: number): Promise<{ day_index: number; day_label: string; exercise_count: number }[]> {
  const db = await getDatabase();
  const rows = await db.getAllAsync<{ day_index: number; day_label: string; exercise_count: number }>(
    `SELECT day_index, COALESCE(NULLIF(day_label, ''), 'Treino') as day_label, COUNT(*) as exercise_count
     FROM plan_exercises WHERE plan_id = ?
     GROUP BY day_index, day_label
     ORDER BY day_index`,
    [planId]
  );
  return rows;
}

/**
 * How many distinct training days each plan has, for every plan at once.
 * Screens listing plans (Planos, Treinar) used to call getPlanDays() once
 * per plan in a loop — one query per plan (N+1) — just to know whether a
 * plan needs a day picker before starting. This does it in a single query
 * regardless of how many plans exist.
 */
export async function getPlanDayCounts(planIds: number[]): Promise<Record<number, number>> {
  if (planIds.length === 0) return {};
  const db = await getDatabase();
  const placeholders = planIds.map(() => '?').join(',');
  const rows = await db.getAllAsync<{ plan_id: number; c: number }>(
    `SELECT plan_id, COUNT(DISTINCT day_index) as c
     FROM plan_exercises WHERE plan_id IN (${placeholders})
     GROUP BY plan_id`,
    planIds
  );
  const result: Record<number, number> = {};
  for (const id of planIds) result[id] = 0;
  for (const row of rows) result[row.plan_id] = row.c;
  return result;
}

export async function getPlanExercisesWithDetails(planId: number): Promise<any[]> {
  const db = await getDatabase();
  const rows = await db.getAllAsync(
    `SELECT pe.*, e.name as exercise_name, e.primary_muscle, e.equipment, e.type, e.user_notes, e.media_uri, e.image_url
     FROM plan_exercises pe
     JOIN exercises e ON pe.exercise_id = e.id
     WHERE pe.plan_id = ?
     ORDER BY pe.day_index, pe.order_index`,
    [planId]
  );
  return rows;
}

export async function addExerciseToPlan(
  planId: number,
  exerciseId: number,
  sets: number,
  repsTarget: string,
  weightTarget: number,
  restSeconds: number,
  setType: SetType,
  supersetGroup: number | null,
  notes: string,
  orderIndex: number,
  dayLabel: string = '',
  dayIndex: number = 0,
  tempo: string = ''
): Promise<number> {
  const db = await getDatabase();
  const result = await db.runAsync(
    `INSERT INTO plan_exercises (plan_id, exercise_id, order_index, sets, reps_target, weight_target, rest_seconds, set_type, superset_group, notes, day_label, day_index, tempo)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [planId, exerciseId, orderIndex, sets, repsTarget, weightTarget, restSeconds, setType, supersetGroup, notes, dayLabel, dayIndex, tempo]
  );
  return result.lastInsertRowId as number;
}

export async function updatePlanExercise(pe: PlanExercise): Promise<void> {
  const db = await getDatabase();
  await db.runAsync(
    `UPDATE plan_exercises SET sets = ?, reps_target = ?, weight_target = ?, rest_seconds = ?, set_type = ?, superset_group = ?, notes = ?, order_index = ?, day_label = ?, day_index = ?, tempo = ? WHERE id = ?`,
    [pe.sets, pe.reps_target, pe.weight_target, pe.rest_seconds, pe.set_type, pe.superset_group, pe.notes, pe.order_index, pe.day_label ?? '', pe.day_index ?? 0, pe.tempo ?? '', pe.id]
  );
}

export async function deletePlanExercise(id: number): Promise<void> {
  const db = await getDatabase();
  await db.runAsync('DELETE FROM plan_exercises WHERE id = ?', [id]);
}

export async function reorderPlanExercises(planId: number, orderedIds: number[]): Promise<void> {
  const db = await getDatabase();
  // Wrapped in a transaction so an interruption partway through can't leave
  // the plan with a mix of old and new order_index values.
  await db.withTransactionAsync(async () => {
    for (let i = 0; i < orderedIds.length; i++) {
      await db.runAsync('UPDATE plan_exercises SET order_index = ? WHERE id = ? AND plan_id = ?', [i, orderedIds[i], planId]);
    }
  });
}
