/**
 * Explicit high-confidence free-exercise-db → GymForge PT seed media bridges.
 * Keys MUST match assets/data/exercise-db.json `name` exactly.
 * Values MUST match db/exerciseSeedData.ts `name` exactly.
 *
 * Used by scripts/enrich_exercise_media.cjs — never invents URLs.
 */
module.exports = {
  // --- Chest / push ---
  Pushups: 'Flexões',
  'Incline Push-Up': 'Flexões Inclinadas',
  'Decline Push-Up': 'Flexões Declinadas',
  'Push-Ups - Close Triceps Position': 'Flexões Diamante',
  'Close-Grip Push-Up off of a Dumbbell': 'Flexões Pegada Fechada',
  'Handstand Push-Ups': 'Flexões em Apoio de Pinheiro',
  'Plyo Push-up': 'Flexões Pliométricas',
  'Push-Ups With Feet Elevated': 'Flexões com Pernas Elevadas',
  'Barbell Bench Press - Medium Grip': 'Supino com Barra',
  'Barbell Incline Bench Press - Medium Grip': 'Supino Inclinado com Barra',
  'Decline Barbell Bench Press': 'Supino Declinado com Barra',
  'Dumbbell Bench Press': 'Supino com Halteres',
  'Incline Dumbbell Press': 'Supino Inclinado com Halteres',
  'Decline Dumbbell Bench Press': 'Supino Declinado com Halteres',
  'Close-Grip Barbell Bench Press': 'Supino Apertado com Barra',
  'Machine Bench Press': 'Supino na Máquina',
  'Smith Machine Incline Bench Press': 'Supino Inclinado na Máquina',
  'Cable Chest Press': 'Press de Peito no Cabo',
  'Dumbbell Flyes': 'Crucifixo com Halteres',
  'Incline Dumbbell Flyes': 'Crucifixo Inclinado com Halteres',
  'Flat Bench Cable Flyes': 'Crossover no Cabo',
  'Low Cable Crossover': 'Crucifixo Declinado com Cabo',
  Butterfly: 'Crucifixo na Máquina (Peck Deck)',
  'Bent-Arm Dumbbell Pullover': 'Pullover com Halter',

  // --- Back / pull ---
  Pullups: 'Barra Fixa (Pull-up)',
  'Chin-Up': 'Barra Fixa Pegada Inversa (Chin-up)',
  'Wide-Grip Rear Pull-Up': 'Barra Fixa Pegada Larga',
  'V-Bar Pullup': 'Barra Fixa Pegada Neutra',
  'Band Assisted Pull-Up': 'Barra Fixa Assistida',
  'Wide-Grip Lat Pulldown': 'Puxada Frontal (Lat Pulldown)',
  'Close-Grip Front Lat Pulldown': 'Puxada Pegada Neutra',
  'Underhand Cable Pulldowns': 'Puxada Pegada Inversa',
  'Wide-Grip Pulldown Behind The Neck': 'Puxada Atrás',
  'Seated Cable Rows': 'Remada no Cabo Baixo',
  'Bent Over Barbell Row': 'Remada Curvada com Barra',
  'Reverse Grip Bent-Over Rows': 'Remada Curvada Pegada Inversa',
  'Bent Over Two-Dumbbell Row': 'Remada com Halteres',
  'One-Arm Dumbbell Row': 'Remada Apoiada no Banco',
  'T-Bar Row with Handle': 'Remada com Barra T',
  'Lying T-Bar Row': 'Remada com Barra na Máquina T',
  'Inverted Row': 'Remada Invertida',
  'Straight-Arm Pulldown': 'Straight Arm Pulldown',
  'One-Arm Long Bar Row': 'Meadows Row',
  'Rack Pulls': 'Rack Pull',
  'Snatch Deadlift': 'Levantamento Terra Pegada Snatch',

  // --- Legs / posterior ---
  'Barbell Deadlift': 'Levantamento Terra',
  'Romanian Deadlift': 'Levantamento Terra Rumano',
  'Sumo Deadlift': 'Levantamento Terra Sumo',
  'Barbell Squat': 'Agachamento com Barra',
  'Dumbbell Squat': 'Agachamento com Halteres',
  'Front Barbell Squat': 'Agachamento Frontal',
  'Goblet Squat': 'Agachamento Goblet',
  'Hack Squat': 'Agachamento na Máquina (Hack)',
  'Plie Dumbbell Squat': 'Agachamento Sumo',
  'Split Squats': 'Agachamento Bulgariano',
  'Bodyweight Walking Lunge': 'Afundadas em Pé',
  'Dumbbell Lunges': 'Afundadas com Halteres',
  'Barbell Lunge': 'Afundadas com Barra',
  'Dumbbell Rear Lunge': 'Afundadas Reversas',
  'Barbell Side Split Squat': 'Afundadas Laterais',
  'Dumbbell Step Ups': 'Step-up com Halteres',
  'Barbell Hip Thrust': 'Hip Thrust com Barra',
  'Barbell Glute Bridge': 'Ponte de Glúteos',
  'Single Leg Glute Bridge': 'Ponte de Glúteos Unilateral',
  'Leg Press': 'Leg Press',
  'Leg Extensions': 'Extensão de Pernas (Leg Extension)',
  'Lying Leg Curls': 'Cadeira Flexora (Leg Curl)',
  'Standing Calf Raises': 'Elevação de Gémeos em Pé',
  'Seated Calf Raise': 'Elevação de Gémeos Sentado',

  // --- Shoulders ---
  'Standing Military Press': 'Press Militar com Barra',
  'Seated Barbell Military Press': 'Press Militar Sentado',
  'Seated Dumbbell Press': 'Press com Halteres',
  'Arnold Dumbbell Press': 'Press Arnold',
  'Smith Machine Overhead Shoulder Press': 'Press de Ombros no Smith',
  'Barbell Shoulder Press': 'Press de Ombros em Pé',
  'Side Lateral Raise': 'Elevação Lateral com Halteres',
  'Front Dumbbell Raise': 'Elevação Frontal com Halteres',
  'Bent Over Low-Pulley Side Lateral': 'Elevação Lateral no Cabo',
  'Front Cable Raise': 'Elevação Frontal no Cabo',
  'Front Plate Raise': 'Elevação Frontal com Disco',
  'Face Pull': 'Face Pull',
  // Same movement pattern as Face Pull; cable demo still is acceptable.
  // (Face Pull no Cabo is filled via inherit/second pass below in enrich — mapped here by alias key)
  'Reverse Flyes': 'Crucifixo Inverso com Halteres',
  'Cable Rear Delt Fly': 'Crucifixo Inverso no Cabo',

  // --- Arms ---
  'Barbell Curl': 'Curl com Barra',
  'Dumbbell Bicep Curl': 'Curl com Halteres',
  'Dumbbell Alternate Bicep Curl': 'Curl Alternado com Halteres',
  'Hammer Curls': 'Curl Martelo com Halteres',
  'Cable Hammer Curls - Rope Attachment': 'Curl Martelo no Cabo',
  'Concentration Curls': 'Curl Concentrado',
  'Preacher Curl': 'Preacher Curl com Barra',
  'One Arm Dumbbell Preacher Curl': 'Preacher Curl com Halter',
  'Machine Preacher Curls': 'Preacher Curl na Máquina',
  'Incline Dumbbell Curl': 'Curl Inclinado com Halteres',
  'Triceps Pushdown': 'Extensão de Tríceps na Polia',
  'Triceps Pushdown - V-Bar Attachment': 'Extensão com Barra V',
  'Triceps Pushdown - Rope Attachment': 'Tríceps no Cabo com Corda',
  'Bench Dips': 'Fundos no Banco',
  'Dips - Triceps Version': 'Fundos de Tríceps',
  'Cable Rope Overhead Triceps Extension': 'Extensão por Cima com Corda',
  'Dumbbell One-Arm Triceps Extension': 'Extensão com Halter Unilateral',
  'EZ-Bar Skullcrusher': 'French Press com Barra EZ',
  'Decline Dumbbell Triceps Extension': 'French Press com Halteres',
  'Tricep Dumbbell Kickback': 'Kickback de Tríceps',
  'Standing Dumbbell Triceps Extension': 'Extensão com Halter por Cima',

  // --- Traps / misc ---
  'Barbell Shrug': 'Encolhimento com Barra',
  'Dumbbell Shrug': 'Encolhimento com Halteres',
  'Cable Shrugs': 'Encolhimento com Cabo',
  'Leverage Shrug': 'Encolhimento na Máquina',
  Plank: 'Prancha',
  'Side Bridge': 'Prancha Lateral',
  Crunches: 'Crunch',
  'Ab Crunch Machine': 'Crunch na Máquina',
  'Hyperextensions (Back Extensions)': 'Hiperextensão',
  'Hanging Leg Raise': 'Hanging Leg Raise',
  'Russian Twist': 'Russian Twist',
  'Air Bike': 'Air Bike',
  'Mountain Climbers': 'Mountain Climbers',
  Superman: 'Superman',
};
